# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Test conditional_steps
on:
  push:
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Set up Python ${{ matrix.python-version }}
      if: ${{ matrix.os }} == "windows-latest"
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
